var searchData=
[
  ['a_20bug_0',['Reporting a bug',['../md_CONTRIBUTING.html#autotoc_md3',1,'']]],
  ['a_20bug_20fix_1',['Contributing a bug fix',['../md_CONTRIBUTING.html#autotoc_md19',1,'']]],
  ['a_20compile_20or_20link_20bug_2',['Reporting a compile or link bug',['../md_CONTRIBUTING.html#autotoc_md4',1,'']]],
  ['a_20context_20creation_20bug_3',['Reporting a context creation bug',['../md_CONTRIBUTING.html#autotoc_md8',1,'']]],
  ['a_20documentation_20bug_4',['Reporting a documentation bug',['../md_CONTRIBUTING.html#autotoc_md16',1,'']]],
  ['a_20feature_5',['a feature',['../md_CONTRIBUTING.html#autotoc_md20',1,'Contributing a feature'],['../md_CONTRIBUTING.html#autotoc_md18',1,'Requesting a feature']]],
  ['a_20loader_20library_6',['Loading extension with a loader library',['../context_guide.html#context_glext_auto',1,'']]],
  ['a_20monitor_20or_20video_20mode_20bug_7',['Reporting a monitor or video mode bug',['../md_CONTRIBUTING.html#autotoc_md10',1,'']]],
  ['a_20question_8',['Asking a question',['../md_CONTRIBUTING.html#autotoc_md2',1,'']]],
  ['a_20segfault_20or_20other_20crash_20bug_9',['Reporting a segfault or other crash bug',['../md_CONTRIBUTING.html#autotoc_md6',1,'']]],
  ['a_20vulkan_20window_20surface_10',['Creating a Vulkan window surface',['../vulkan_guide.html#vulkan_surface',1,'']]],
  ['a_20website_20bug_11',['Reporting a website bug',['../md_CONTRIBUTING.html#autotoc_md17',1,'']]],
  ['a_20window_20and_20context_12',['Creating a window and context',['../quick_guide.html#quick_create_window',1,'']]],
  ['a_20window_20input_20or_20event_20bug_13',['Reporting a window, input or event bug',['../md_CONTRIBUTING.html#autotoc_md12',1,'']]],
  ['action_14',['Key repeat action',['../moving_guide.html#moving_repeat',1,'']]],
  ['actions_15',['Removal of character actions',['../moving_guide.html#moving_char_up',1,'']]],
  ['allocator_16',['Custom heap memory allocator',['../intro_guide.html#init_allocator',1,'']]],
  ['an_20error_20callback_17',['Setting an error callback',['../quick_guide.html#quick_capture_error',1,'']]],
  ['and_20api_18',['Vulkan loader and API',['../compat_guide.html#compat_vulkan',1,'']]],
  ['and_20close_20flag_19',['Window closing and close flag',['../window_guide.html#window_close',1,'']]],
  ['and_20context_20',['Creating a window and context',['../quick_guide.html#quick_create_window',1,'']]],
  ['and_20default_20values_21',['and default values',['../window_guide.html#window_hints_values',1,'Supported and default values'],['../intro_guide.html#init_hints_values',1,'Supported and default values']]],
  ['and_20events_22',['Window properties and events',['../window_guide.html#window_properties',1,'']]],
  ['and_20framebuffer_20sizes_23',['Separation of window and framebuffer sizes',['../moving_guide.html#moving_hidpi',1,'']]],
  ['and_20glfw_20binaries_24',['and glfw binaries',['../build_guide.html#build_link_mingw',1,'With MinGW-w64 and GLFW binaries'],['../build_guide.html#build_link_win32',1,'With Visual C++ and GLFW binaries']]],
  ['and_20glfw_20binaries_20on_20unix_25',['With pkg-config and GLFW binaries on Unix',['../build_guide.html#build_link_pkgconfig',1,'']]],
  ['and_20glfw_20source_26',['With CMake and GLFW source',['../build_guide.html#build_link_cmake_source',1,'']]],
  ['and_20header_20file_27',['Renamed library and header file',['../moving_guide.html#moving_renamed_files',1,'']]],
  ['and_20installed_20glfw_20binaries_28',['With CMake and installed GLFW binaries',['../build_guide.html#build_link_cmake_package',1,'']]],
  ['and_20ipc_20standards_29',['and ipc standards',['../compat_guide.html#compat_wayland',1,'Wayland protocols and IPC standards'],['../compat_guide.html#compat_x11',1,'X11 extensions, protocols and IPC standards']]],
  ['and_20limitations_30',['Guarantees and limitations',['../intro_guide.html#guarantees_limitations',1,'']]],
  ['and_20mingw_31',['Cross-compilation with CMake and MinGW',['../compile_guide.html#compile_mingw_cross',1,'']]],
  ['and_20opengl_20es_20extensions_32',['OpenGL and OpenGL ES extensions',['../context_guide.html#context_glext',1,'']]],
  ['and_20output_33',['Clipboard input and output',['../input_guide.html#clipboard',1,'']]],
  ['and_20refresh_34',['Window damage and refresh',['../window_guide.html#window_refresh',1,'']]],
  ['and_20removed_20features_35',['Changed and removed features',['../moving_guide.html#moving_removed',1,'']]],
  ['and_20soft_20constraints_36',['Hard and soft constraints',['../window_guide.html#window_hints_hard',1,'']]],
  ['and_20terminating_20glfw_37',['Initializing and terminating GLFW',['../quick_guide.html#quick_init_term',1,'']]],
  ['and_20termination_38',['Initialization and termination',['../intro_guide.html#intro_init',1,'']]],
  ['and_20texture_20loading_39',['Removal of image and texture loading',['../moving_guide.html#moving_image',1,'']]],
  ['and_20x11_40',['Dependencies for Wayland and X11',['../compile_guide.html#compile_deps_wayland',1,'']]],
  ['api_41',['api',['../intro_guide.html',1,'Introduction to the API'],['../compat_guide.html#compat_vulkan',1,'Vulkan loader and API']]],
  ['applications_42',['Building applications',['../build_guide.html',1,'']]],
  ['area_43',['Work area',['../monitor_guide.html#monitor_workarea',1,'']]],
  ['asking_20a_20question_44',['Asking a question',['../md_CONTRIBUTING.html#autotoc_md2',1,'']]],
  ['attention_20request_45',['Window attention request',['../window_guide.html#window_attention',1,'']]],
  ['attributes_46',['attributes',['../window_guide.html#window_attribs_ctx',1,'Context related attributes'],['../window_guide.html#window_attribs_fb',1,'Framebuffer related attributes'],['../window_guide.html#window_attribs',1,'Window attributes'],['../window_guide.html#window_attribs_wnd',1,'Window related attributes']]],
  ['automatic_20event_20polling_47',['Removal of automatic event polling',['../moving_guide.html#moving_autopoll',1,'']]],
  ['automatic_20termination_48',['Automatic termination',['../moving_guide.html#moving_terminate',1,'']]],
  ['axis_20states_49',['Joystick axis states',['../input_guide.html#joystick_axis',1,'']]]
];
